### AUTH ENDPOINT
### Register a User
POST  http://localhost:3874/auth/register
Content-Type: application/json

{
    "email":"",
    "username":"",
    "password":""
}

### Login a User
POST  http://localhost:3874/auth/login
Content-Type: application/json

{
    "email":"",
    "password":""
}
### Logout a User
POST  http://localhost:3874/auth/logout


### CRUD
### USER ENDPOINT
### Update user data (same user auth)
PATCH   http://localhost:3874/users/update
Content-Type: application/json
Authorization: Bearer 

{
    "email":"",
    "username":"",
    "password":""
}
### Remove a User (same user auth)
DELETE  http://localhost:3874/users/remove
Content-Type: application/json
Authorization: Bearer 

{
    "password":""
}
### WATCHLIST ENDPOINT
### get user watchlist (same user auth)
GET  http://localhost:3874/watchLists/
Authorization: Bearer 
### get user watchlist Item (same user auth)
GET  http://localhost:3874/watchLists/id
Authorization: Bearer 

### Add movie to watchlist (same user auth)
POST  http://localhost:3874/watchLists/
Content-Type: application/json
Authorization: Bearer 
{
    "movieId":"16afaa70-82e0-4c07-ac3c-ad646854378e",
    "rating": 8
}

### update watchlist Item (same user auth)
PATCH http://localhost:3874/watchLists/id
Content-Type:application/json
Authorization: Bearer 

{
    "rating":90,
    "status":"blablabla",
    "notes":23.2
}
### delete watchlist Item (same user auth)
DELETE http://localhost:3874/watchLists/id
Content-Type: application/json
Authorization: Bearer 

### MOVIES ENDPOINT
### get all movies (same user auth)
GET http://localhost:3874/movies/
Authorization: Bearer 
### get a movie by id (same user auth)
GET http://localhost:3874/movies/id
Authorization: Bearer 
### add a movie (admin auth)
POST http://localhost:3874/movies/
Content-Type: application/json
Authorization: Bearer 

{

}
### update a movie by id (admin auth)
PATCH  http://localhost:3874/movies/id
Content-Type: application/json
Authorization: Bearer 

{

}
### delete a movie by id (admin auth)
DELETE   http://localhost:3874/movies/id
Authorization: Bearer 

### ADMIN ENDPOINT
### Promote a user to admin (admin auth required) 
PATCH http://localhost:3874/admin/users/promote/id
Content-Type: application/json
Authorization: Bearer

{
    "role": "ADMIN"
}